name: NPM Publish Beta

on: workflow_dispatch

jobs:
  publish-npm-beta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: cp ./README.md ./src/README.md
      - run: npm install
        working-directory: ./src
      - run: npm publish --tag beta --dry-run
        working-directory: ./src
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
